# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductCatalogStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProductByName = channel.unary_unary(
                '/ProductCatalog/GetProductByName',
                request_serializer=service__pb2.ProductRequest.SerializeToString,
                response_deserializer=service__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.GetProductsByPrice = channel.unary_unary(
                '/ProductCatalog/GetProductsByPrice',
                request_serializer=service__pb2.PriceRequest.SerializeToString,
                response_deserializer=service__pb2.ProductList.FromString,
                _registered_method=True)
        self.UpdateProductStock = channel.unary_unary(
                '/ProductCatalog/UpdateProductStock',
                request_serializer=service__pb2.UpdateStockRequest.SerializeToString,
                response_deserializer=service__pb2.UpdateResponse.FromString,
                _registered_method=True)


class ProductCatalogServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetProductByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductsByPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProductStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductCatalogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProductByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductByName,
                    request_deserializer=service__pb2.ProductRequest.FromString,
                    response_serializer=service__pb2.ProductResponse.SerializeToString,
            ),
            'GetProductsByPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductsByPrice,
                    request_deserializer=service__pb2.PriceRequest.FromString,
                    response_serializer=service__pb2.ProductList.SerializeToString,
            ),
            'UpdateProductStock': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProductStock,
                    request_deserializer=service__pb2.UpdateStockRequest.FromString,
                    response_serializer=service__pb2.UpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ProductCatalog', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ProductCatalog', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductCatalog(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProductByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProductCatalog/GetProductByName',
            service__pb2.ProductRequest.SerializeToString,
            service__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProductsByPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProductCatalog/GetProductsByPrice',
            service__pb2.PriceRequest.SerializeToString,
            service__pb2.ProductList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProductStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ProductCatalog/UpdateProductStock',
            service__pb2.UpdateStockRequest.SerializeToString,
            service__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
