# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x1e\n\x0eProductRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\x0cPriceRequest\x12\x11\n\tmax_price\x18\x01 \x01(\x02\"5\n\x12UpdateStockRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tnew_stock\x18\x02 \x01(\x05\"5\n\x07Product\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\x12\r\n\x05stock\x18\x03 \x01(\x05\",\n\x0fProductResponse\x12\x19\n\x07product\x18\x01 \x01(\x0b\x32\x08.Product\")\n\x0bProductList\x12\x1a\n\x08products\x18\x01 \x03(\x0b\x32\x08.Product\"!\n\x0eUpdateResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb6\x01\n\x0eProductCatalog\x12\x35\n\x10GetProductByName\x12\x0f.ProductRequest\x1a\x10.ProductResponse\x12\x31\n\x12GetProductsByPrice\x12\r.PriceRequest\x1a\x0c.ProductList\x12:\n\x12UpdateProductStock\x12\x13.UpdateStockRequest\x1a\x0f.UpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTREQUEST']._serialized_start=17
  _globals['_PRODUCTREQUEST']._serialized_end=47
  _globals['_PRICEREQUEST']._serialized_start=49
  _globals['_PRICEREQUEST']._serialized_end=82
  _globals['_UPDATESTOCKREQUEST']._serialized_start=84
  _globals['_UPDATESTOCKREQUEST']._serialized_end=137
  _globals['_PRODUCT']._serialized_start=139
  _globals['_PRODUCT']._serialized_end=192
  _globals['_PRODUCTRESPONSE']._serialized_start=194
  _globals['_PRODUCTRESPONSE']._serialized_end=238
  _globals['_PRODUCTLIST']._serialized_start=240
  _globals['_PRODUCTLIST']._serialized_end=281
  _globals['_UPDATERESPONSE']._serialized_start=283
  _globals['_UPDATERESPONSE']._serialized_end=316
  _globals['_PRODUCTCATALOG']._serialized_start=319
  _globals['_PRODUCTCATALOG']._serialized_end=501
# @@protoc_insertion_point(module_scope)
